import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import { useAccount, useProvider } from 'wagmi'
import { Text, Flex, Button } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useState } from 'react'
import { ethers } from 'ethers'
import { contractAddress, abi } from "../public/constants"

export default function getTheNumber() {

  const { address, isConnected } = useAccount()
  const provider = useProvider()

  const [number, setNumber] = useState(null)

  const getTheNumber = async() => {
    const contract = new ethers.Contract(contractAddress, abi, provider)
    let smartContractValue = await contract.getNumber()
    setNumber(smartContractValue.toString())
  }
  
  return (
    <>
      <Head>
        <title>Alyra DApp : Get the number</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
          <Flex alignItems="center">
            <Button colorScheme='blue' onClick={() => getTheNumber()}>Get the number</Button>
            {number ? (
                <Text ml="1rem">{number}</Text> 
            ) : (
                <Text ml="1rem">Please, click on this button to get the number.</Text>
            )}
          </Flex>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}
