import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import MyPlan from '@/components/MyPlan/MyPlan'
import { useAccount, useProvider, useSigner } from 'wagmi'
import { Text } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'

export default function Home() {

  const { address, isConnected } = useAccount()
  
  return (
    <>
      <Head>
        <title>Alyra DApp : Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
          <MyPlan>Welcome on Alyra DApp !</MyPlan>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet!
          </Alert>
        )}
      </Layout>
    </>
  )
}
