import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import Layout from '@/components/Layout/Layout'
import { useAccount, useSigner } from 'wagmi'
import { Text, Flex, Button, Input, useToast } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useState } from 'react'
import { ethers } from 'ethers'
import { contractAddress, abi } from "../public/constants"

export default function setTheNumber() {

  const { address, isConnected } = useAccount()
  const { data: signer } = useSigner()
  const toast = useToast()
  const router = useRouter()

  const [number, setNumber] = useState(null)

  const setTheNumber = async() => {
    try {
        const contract = new ethers.Contract(contractAddress, abi, signer)
        let transaction = await contract.setNumber(number)
        await transaction.wait()
        router.push('/getNumber')
        toast({
            title: 'Congratulations',
            description: "the number has been changed!",
            status: 'success',
            duration: 9000,
            isClosable: true,
        })
    }
    catch(e) {
        toast({
            title: 'Error',
            description: "An error occured.",
            status: 'error',
            duration: 9000,
            isClosable: true,
        })
        console.log(e)
    }
    
  }
  
  return (
    <>
      <Head>
        <title>Alyra DApp : Set the number</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {isConnected ? (
          <Flex alignItems="center">
            <Input placeholder='Your number...' onChange={(e) => setNumber(e.target.value)} />
            <Button colorScheme='blue' onClick={() => setTheNumber()}>Set</Button>
          </Flex>
        ) : (
          <Alert status='warning' width="50%">
            <AlertIcon />
            Please, connect your Wallet.
          </Alert>
        )}
      </Layout>
    </>
  )
}
